### ISSUE TITLE
ProperCase outgoing parameters

### ISSUE THREAD

**Issue by smithaitufe** [johnnyji/proper_case#2]
I want to find out if this library supports outgoing case. I mean how will the js client side receive the properties of the object?

**Comment by smdern** [comment]
I've created a plug that does just that. I'll try and get a PR open with the plug

 Example usage. 

``` elixir
plug TransformParams,
  params: &ProperCase.to_snake_case/1,
  response: [
    json: &ProperCase.to_camel_case/1,
    plain_text: &String.upcase/1,
  ]
```

**Comment by johnnyji** [comment]
@smdern Sounds amazing! Please do, @smithaitufe would this sufficiently solve the problem you're having?

**Comment by smithaitufe** [comment]
@johnnyji that will be lovely. I actually had this mind as a project. When I saw your library, I was proud I thought I like you. @smdern Thanks. I am available for contributions.

**Comment by smdern** [comment]
@smithaitufe  https://gist.github.com/smdern/2b8fbf857c23ea2ab03727ee9a0d43db

I'm going to create a plug that deals w/ transform request/response. It's probably not appropriate enforce more deps for proper_case and would be better suited as a companion dep

**Comment by smdern** [comment]
I ended up coming up with a better solution for using proper_case before encoding to JSON in phoenix. https://github.com/johnnyji/proper_case/pull/5

**Comment by johnnyji** [comment]
@smithaitufe @smdern Merged and updated on Hex.

@smdern Thanks for all the contributions :)
